#ifndef MANIPULATEFILE_GLOBAL_H
#define MANIPULATEFILE_GLOBAL_H


#include <QtCore/qglobal.h>

#if defined(MANIPULATEFILE_LIBRARY)
#  define MANIPULATEFILE_EXPORT Q_DECL_EXPORT
#else
#  define MANIPULATEFILE_EXPORT Q_DECL_IMPORT
#endif



#endif // MANIPULATEFILE_GLOBAL_H
